name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "frontend-react/**"
      - "backend/**"

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    if: "contains(toJSON(github.event.commits).*.modified, 'frontend-react/')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --prefix frontend-react

      - name: Build React app
        run: npm run build --prefix frontend-react

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Transfer build folder to DigitalOcean Droplet
        env:
          DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          DROPLET_IP_ADDRESS: ${{ secrets.DROPLET_IP_ADDRESS }}
        run: |
          echo "$DROPLET_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --delete frontend-react/build/ root@$DROPLET_IP_ADDRESS:/var/www/html/
          rm -f private_key

  deploy_backend:
    runs-on: ubuntu-latest
    if: "contains(toJSON(github.event.commits).*.modified, 'backend/')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Transfer backend folder to DigitalOcean Droplet (excluding node_modules)
        env:
          DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          DROPLET_IP_ADDRESS: ${{ secrets.DROPLET_IP_ADDRESS }}
        run: |
          echo "$DROPLET_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz --exclude 'node_modules' -e "ssh -i private_key -o StrictHostKeyChecking=no" --delete backend/ root@$DROPLET_IP_ADDRESS:~/my-express-server
          rm -f private_key

      - name: Install dependencies on the VM
        env:
          DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          DROPLET_IP_ADDRESS: ${{ secrets.DROPLET_IP_ADDRESS }}
        run: |
          echo "$DROPLET_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no root@$DROPLET_IP_ADDRESS 'cd ~/my-express-server && npm ci'
          rm -f private_key

      - name: Start or restart backend on DigitalOcean Droplet
        env:
          DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          DROPLET_IP_ADDRESS: ${{ secrets.DROPLET_IP_ADDRESS }}
        run: |
          echo "$DROPLET_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no root@$DROPLET_IP_ADDRESS 'cd ~/my-express-server && pm2 restart backend'
          rm -f private_key
